/*
 * poe.ninja API
 *
 * Public API of poe.ninja (mainly economy for now).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PoeNinjaApi.Client.OpenAPIDateConverter;

namespace PoeNinjaApi.Model
{
    /// <summary>
    /// ItemModel
    /// </summary>
    [DataContract(Name = "ItemModel")]
    public partial class ItemModel : IEquatable<ItemModel>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets ItemSlot
        /// </summary>
        [DataMember(Name = "itemSlot", IsRequired = true, EmitDefaultValue = false)]
        public ItemSlot ItemSlot { get; set; }
        /// <summary>
        /// Gets or Sets ItemClass
        /// </summary>
        [DataMember(Name = "itemClass", IsRequired = true, EmitDefaultValue = false)]
        public ItemClass ItemClass { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ItemModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemModel" /> class.
        /// </summary>
        /// <param name="itemData">itemData.</param>
        /// <param name="itemSlot">itemSlot (required).</param>
        /// <param name="itemClass">itemClass (required).</param>
        public ItemModel(ItemData itemData = default(ItemData), ItemSlot itemSlot = default(ItemSlot), ItemClass itemClass = default(ItemClass))
        {
            this.ItemSlot = itemSlot;
            this.ItemClass = itemClass;
            this.ItemData = itemData;
        }

        /// <summary>
        /// Gets or Sets ItemData
        /// </summary>
        [DataMember(Name = "itemData", EmitDefaultValue = false)]
        public ItemData ItemData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemModel {\n");
            sb.Append("  ItemData: ").Append(ItemData).Append("\n");
            sb.Append("  ItemSlot: ").Append(ItemSlot).Append("\n");
            sb.Append("  ItemClass: ").Append(ItemClass).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ItemModel);
        }

        /// <summary>
        /// Returns true if ItemModel instances are equal
        /// </summary>
        /// <param name="input">Instance of ItemModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ItemData == input.ItemData ||
                    (this.ItemData != null &&
                    this.ItemData.Equals(input.ItemData))
                ) && 
                (
                    this.ItemSlot == input.ItemSlot ||
                    this.ItemSlot.Equals(input.ItemSlot)
                ) && 
                (
                    this.ItemClass == input.ItemClass ||
                    this.ItemClass.Equals(input.ItemClass)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ItemData != null)
                    hashCode = hashCode * 59 + this.ItemData.GetHashCode();
                hashCode = hashCode * 59 + this.ItemSlot.GetHashCode();
                hashCode = hashCode * 59 + this.ItemClass.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
