/*
 * poe.ninja API
 *
 * Public API of poe.ninja (mainly economy for now).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PoeNinjaApi.Client.OpenAPIDateConverter;

namespace PoeNinjaApi.Model
{
    /// <summary>
    /// SocketedItemDataAllOf
    /// </summary>
    [DataContract(Name = "SocketedItemData_allOf")]
    public partial class SocketedItemDataAllOf : IEquatable<SocketedItemDataAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SocketedItemDataAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SocketedItemDataAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SocketedItemDataAllOf" /> class.
        /// </summary>
        /// <param name="socket">socket (required).</param>
        /// <param name="colour">colour.</param>
        public SocketedItemDataAllOf(int socket = default(int), string colour = default(string))
        {
            this.Socket = socket;
            this.Colour = colour;
        }

        /// <summary>
        /// Gets or Sets Socket
        /// </summary>
        [DataMember(Name = "socket", IsRequired = true, EmitDefaultValue = false)]
        public int Socket { get; set; }

        /// <summary>
        /// Gets or Sets Colour
        /// </summary>
        [DataMember(Name = "colour", EmitDefaultValue = false)]
        public string Colour { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SocketedItemDataAllOf {\n");
            sb.Append("  Socket: ").Append(Socket).Append("\n");
            sb.Append("  Colour: ").Append(Colour).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SocketedItemDataAllOf);
        }

        /// <summary>
        /// Returns true if SocketedItemDataAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of SocketedItemDataAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SocketedItemDataAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Socket == input.Socket ||
                    this.Socket.Equals(input.Socket)
                ) && 
                (
                    this.Colour == input.Colour ||
                    (this.Colour != null &&
                    this.Colour.Equals(input.Colour))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Socket.GetHashCode();
                if (this.Colour != null)
                    hashCode = hashCode * 59 + this.Colour.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
