/*
 * poe.ninja API
 *
 * Public API of poe.ninja (mainly economy for now).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PoeNinjaApi.Client.OpenAPIDateConverter;

namespace PoeNinjaApi.Model
{
    /// <summary>
    /// SparkLineInfo
    /// </summary>
    [DataContract(Name = "SparkLineInfo")]
    public partial class SparkLineInfo : IEquatable<SparkLineInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SparkLineInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SparkLineInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SparkLineInfo" /> class.
        /// </summary>
        /// <param name="data">data.</param>
        /// <param name="totalChange">totalChange (required).</param>
        public SparkLineInfo(List<decimal> data = default(List<decimal>), decimal totalChange = default(decimal))
        {
            this.TotalChange = totalChange;
            this.Data = data;
        }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public List<decimal> Data { get; set; }

        /// <summary>
        /// Gets or Sets TotalChange
        /// </summary>
        [DataMember(Name = "totalChange", IsRequired = true, EmitDefaultValue = false)]
        public decimal TotalChange { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SparkLineInfo {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  TotalChange: ").Append(TotalChange).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SparkLineInfo);
        }

        /// <summary>
        /// Returns true if SparkLineInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of SparkLineInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SparkLineInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Data == input.Data ||
                    this.Data != null &&
                    input.Data != null &&
                    this.Data.SequenceEqual(input.Data)
                ) && 
                (
                    this.TotalChange == input.TotalChange ||
                    this.TotalChange.Equals(input.TotalChange)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Data != null)
                    hashCode = hashCode * 59 + this.Data.GetHashCode();
                hashCode = hashCode * 59 + this.TotalChange.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
