/*
 * poe.ninja API
 *
 * Public API of poe.ninja (mainly economy for now).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PoeNinjaApi.Client.OpenAPIDateConverter;

namespace PoeNinjaApi.Model
{
    /// <summary>
    /// TradeInfo
    /// </summary>
    [DataContract(Name = "TradeInfo")]
    public partial class TradeInfo : IEquatable<TradeInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TradeInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TradeInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TradeInfo" /> class.
        /// </summary>
        /// <param name="mod">mod.</param>
        /// <param name="min">min (required).</param>
        /// <param name="max">max (required).</param>
        public TradeInfo(string mod = default(string), int min = default(int), int max = default(int))
        {
            this.Min = min;
            this.Max = max;
            this.Mod = mod;
        }

        /// <summary>
        /// Gets or Sets Mod
        /// </summary>
        [DataMember(Name = "mod", EmitDefaultValue = false)]
        public string Mod { get; set; }

        /// <summary>
        /// Gets or Sets Min
        /// </summary>
        [DataMember(Name = "min", IsRequired = true, EmitDefaultValue = false)]
        public int Min { get; set; }

        /// <summary>
        /// Gets or Sets Max
        /// </summary>
        [DataMember(Name = "max", IsRequired = true, EmitDefaultValue = false)]
        public int Max { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TradeInfo {\n");
            sb.Append("  Mod: ").Append(Mod).Append("\n");
            sb.Append("  Min: ").Append(Min).Append("\n");
            sb.Append("  Max: ").Append(Max).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TradeInfo);
        }

        /// <summary>
        /// Returns true if TradeInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of TradeInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TradeInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Mod == input.Mod ||
                    (this.Mod != null &&
                    this.Mod.Equals(input.Mod))
                ) && 
                (
                    this.Min == input.Min ||
                    this.Min.Equals(input.Min)
                ) && 
                (
                    this.Max == input.Max ||
                    this.Max.Equals(input.Max)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Mod != null)
                    hashCode = hashCode * 59 + this.Mod.GetHashCode();
                hashCode = hashCode * 59 + this.Min.GetHashCode();
                hashCode = hashCode * 59 + this.Max.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
